font-engine=pango
font-name=DejaVu Sans Mono
font-size=16
font-dpi=96
term=xterm-256color
palette=custom
palette-black=0,0,0
palette-red=204,68,68
palette-green=153,204,255
palette-yellow=255,153,0
palette-blue=108,127,224
palette-magenta=204,153,204
palette-cyan=153,204,255
palette-light-grey=255,204,153
palette-dark-grey=92,92,122
palette-light-red=221,102,68
palette-light-green=204,221,255
palette-light-yellow=255,204,0
palette-light-blue=153,153,255
palette-light-magenta=153,68,255
palette-light-cyan=204,221,255
palette-white=245,246,250
palette-foreground=255,204,153
palette-background=0,0,0
